name: catelog service

on:
  push:
    paths:
      - catelog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catelog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x ./catelog-service/mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify
        working-directory: ./catelog-service


#      - name: Build with Maven
#        run: ./mvnw -ntp verify