name: catelog service

on:
  push:
    paths:
      - catelog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catelog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory}}
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup java 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Grant execute permission for mvnw
#        run: chmod +x ./catelog-service/mvnw
#
#      - name: Build and verify with Maven
#        run: ./mvnw -ntp verify
#        working-directory: ./catelog-service
#      # .github/workflows/catelog-service.yml
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Make mvnw executable
          run: chmod +x ./mvnw

        # Your existing mvnw usage
        - name: Build with Maven wrapper
          run: ./mvnw clean install

#      - name: Build with Maven
#        run: ./mvnw -ntp verify